[package]
name = "aidbox"
version = "0.1.0"
authors = ["niquola <niquola@gmail.com>"]

[dependencies]
serde_json = "1.0"
chrono = "0.4"
colored = "1.7.0"
hyper = "0.12"
clap = "2.33.0"
base64 = "0.10.1"

[profile.release]
lto = true
panic = 'abort'